version: 0.0
os: linux

files:
  - source: /webapp/target/final.war
    destination: /home/centos/tomcat/webapps
  - source: cloudwatch_config.json
    destination: /home/centos/tomcat
  - source: /webapp/__pycache__/lambda_function.cpython-37.pyc
    destination: /home/centos

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
