version: 0.0
os: linux

files:
  - source: /home/circleci/project/webapp/target/final.war
    destination: /home/centos/tomcat/webapps

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
