version: 0.0
os: linux

files:
  - source: /webapp/target/final.war
    destination: /home/centos/tomcat/webapps
  - source: config-cloudwatch.json
    destination: /home/centos/tomcat

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
