version: 2
jobs:
  build:
    branches:
      only:
        - assignment7
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install openjdk-8-jdk
            sudo apt-get install maven zip unzip -y

      - run:
          name: Install AWS-CLI
          command: |
            sudo pip install awscli

      - run:
          name: Build Artifact
          command: |
            cd webapp
            mvn clean install -Pprod

      - run:
          name: Zip Artifact
          command: |
            mkdir -p codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.sh .
            cp infrastructure/aws/codedeploy/*.json .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip webapp/target/final.war *.sh *.yml *.json
            mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/

      - run:
          name: Upload Artifact to S3
          command: |
            echo "uploading artifact"
            aws s3 cp codedeploy_artifact/csye6225-web-app-${CIRCLE_BUILD_NUM}.zip s3://${CODE_DEPLOY_BUCKET}

      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy"
            aws configure set region ${AWS_REGION}
            aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name csye6225-webapp-deployment --s3-location bucket=${CODE_DEPLOY_BUCKET},bundleType=zip,key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip